spring:
  mail:
    host: poczta.interia.pl
    port: 465
    username: janektester@interia.pl
    password: "kuba1981"
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: true
